### ISSUE TITLE
[Bug] diag_log and other daig_* commands are incorrectly identified without the '_'

### ISSUE THREAD

**Issue by Sniperhid** [AnthonyPoschen/brackets-sqf#1]
The following sqf commands (possibly more):
diag_log
diag_fps
diag_fpsmin
diag_frameno
diag_tickTime
(And mostly likely any other diag_\* )

are listed in both autocomplete and are syntax highlighted for:
diaglog
diagfps
diagfpsmin
diagframeno
diagtickTime

Quickdocs also doesn't work for them, This is a really minor issue but it would be fantastic to see these fixed!

Lastly huge thanks for making this awesome extension, I am using it for my sqf projects :D!

**Comment by AnthonyPoschen** [comment]
thanks man. i did do that part manually. ill just modify my web scraper that gets the docs to also spit out the autocomplete. (sorry late reply life has been pretty hectic lately :p)

**Comment by AnthonyPoschen** [comment]
again huge thanks for reporting the issue hope you enjoy the plugin. problem is resolved in current live build. :). 1.0.0 (yes decided to start using proper version formats :P)

**Comment by Sniperhid** [comment]
Big thanks man for fixing this :)! Never worry about 'replying late' we have all have lives :)! There is only one of other thing I think that can improved but  I'll make a separate ticket for it.
