### ISSUE TITLE
Multi-Line string support

### ISSUE THREAD

**Issue by Sniperhid** [AnthonyPoschen/brackets-sqf#2]
One thing I would love to see is that multi-line strings get recognized properly, sqf does indeed support them. For example here is a snippet from the F3 Arma 3 mission framework, it has a multi-line string in it but the sqm highlighter doesn't pick it up:

```
_cre = player createDiaryRecord ["diary", ["Credits","
<br/>
*** Insert mission credits here. ***
<br/><br/>
Made with F3 (http://www.ferstaberinde.com/f3/en/)
"]];
```

I have no idea how easy this is to implement, but it isn't a huge problem. Though it would be really neat if your brackets extension supported it!

Once again thanks for this awesome extension!

**Comment by AnthonyPoschen** [comment]
the way it is currently setup is that it gets "streams" of chars. for only that line. so you hit null when you go past the end. a option to have a variable stored to say hey we haven't closed the quote for the comment. and which type of quotation. is a option. but this could lead to interesting issues if a quote doesn't end on one file. and you switch files. but if setup correctly that shouldn't be a issue. ill stop watching videos and try and finish it before bed or ill do it tomorrow. also thanks alot man for the support. glad someone likes using it :p.

**Comment by AnthonyPoschen** [comment]
well i have it semi working. the main problem is. the way it works is it constantly rechecks. and does alot of single line checks and a full file check. to try and have syntax highlighting really fast regardless of file size. which causes it to flicker between wrong and correct multi line commenting. might come back to this sometime in the near future.

**Comment by Sniperhid** [comment]
Thanks for taking a look, I greatly appreciate that! Not to worry your extension is awesome enough without this enhancement :)!

**Comment by AnthonyPoschen** [comment]
thanks :). im currently working on a bot to catch hackers (partially) works pretty well on the altis life server i play on. but its main roll will be to let servers sync ban lists between each other. and have filters to pick which ban reasons they are after. i.e bans containing the word "hack" in reason. main reason for doing it. want to learn web programming and get better at Golang which ive only just started using.

not really doing many best practices and ive already seen so many things i can redo and make better as im learning more about the language. but im just gonna power through and finish it. then re write it after and see what i can make easier to read and maintain. and make it more testable.

**Comment by AnthonyPoschen** [comment]
archiving this repo so closing issues.
